#+TITLE: Punteros en C

* Conceptos
** Memoria Estática vs Dinámica
*** Memoria Estática
    La memoria estática es la que se reserva al *declarar variables* de cualquier tipo de datos,
    incluso así las estructuras (en struct) y también los *punteros* a tipos de datos.
    Y se aloja en el *Stack del proceso*, no se puede modificar el espacio en memoria que ocupan ni tampoco liberarla.
*** Memoria Dinámica
    Se reserva en *tiempo de ejecución* y se reserva en el *heap* del proceso.
    (los datos apuntados por los punteros). Y se debe reservar la memoria y liberarla.
** Malloc

   #+BEGIN_EXAMPLE
   la n dentro de la función malloc sirve para hacer en ese ejemplo asignación de memoria 
   de la cantidad de caracteres que se quiere; en efecto se pide el valor de n para que se sepa
   cuántos caracteres tendrá la cadena, seguido esto se multiplica n*sizeof(char) para hacer
   la reserva en cantidad de memoria de n caracteres:
   por ejemplo si la cadena tendrá 10 caracteres y se quiere reservar memoria dinámicamente
   entonces la función será:

   char* p;
   n=10;
   p=(char*)malloc(n*sizeof(char)); /*Reserva memoria para 10 caracteres*/
   #+END_EXAMPLE

   #+NAME: Ejemplo 1
   #+BEGIN_SRC C
     int *p = malloc(sizeof(int));
     int a = 5;
     p = &a;

     //&p (La direccion de memoria de P)
     //p (Guarda UNA direccion de memoria)
     //*p (Muestra/Modifica el valor que contiene UNA direccion de memoria)
     printf("El objeto de la direccion en memoria que se le asigno a (En este caso es &a) p = %d\n", *p);
     printf("La direccion de memoria de a = %p\n", &a);
     printf("El objeto (En este caso una memoria) de p (%%p lo muestra en hexadecimal) = %p\n", p);
     printf("La direccion de memoria de p = %p\n", &p);
     return 0;
   #+END_SRC

   #+NAME: Ejemplo 2
   #+BEGIN_SRC C
     // Compiled with: gcc -std=c11 -Wall -pthread -lm

     #include <stdio.h>
     #include <stdlib.h>


     int main(void){
       int *p1 = malloc(sizeof(int));
       int *p2 = malloc(sizeof(int));
       *p1 = 5;
       *p2 = 6;
       printf("memorias: %p %p %d %p %d\n", &p1, p1, *p1, p2, *p2);

       int *aux = p1;
       p1 = p2;
       p2 = aux;

       printf("memorias: %p %d %p %d", p1, *p1, p2, *p2);

       return 0;
     }
   #+END_SRC

   #+NAME: Ejemplo 3
   #+BEGIN_SRC C
     #include <string.h>
     #include <stdio.h>
     #include <stdlib.h>

     int main(void){
       // reservamos memoria para
       int **padre = malloc(sizeof(int*) * 4);

       for(int i = 0; i < 4; i++)
         *(padre+i) = malloc(sizeof(int));

       for(int i = 0; i < 4; i++)
         **(padre + i) = i * 20;

       for(int i = 0; i < 4; i++){
         printf("El valor de la direccion: ");
         printf("%p es %d\n", *(padre+i), **(padre + i));
       }

       return 0;
     }
   #+END_SRC

*** Referencias
    + [[https://aprenderaprogramar.com/foros/index.php?topic=288.0][Aprende a programar - Malloc]]
    + [[https://www.learn-c.org/en/Arrays_and_Pointers][Arrays and Pointers - learn-c.org]]
** GetLine Vs. fgets
  
   #+NAME: Ejemplo de fgets
   #+BEGIN_SRC C
     char strArray[LONGITUD];
     // reservamos memoria para un arreglo
     // de caracteres con capacidad de 
     // 
     char *strPtr = malloc(sizeof(char));
  
     printf("Inserte texto: ");
     fgets(strArray, LONGITUD, stdin);  
     printf("\n\n\ntexto escrito: %s\n", strArray);

     printf("\n\n\nInserte texto: ");
     fgets(strPtr, LONGITUD, stdin);
     printf("\n\n\ntexto escrito: %s", strPtr);
   #+END_SRC
** Fuga de Memoria (Memory leaks)
*** Explicaciones by friends

    #+BEGIN_EXAMPLE
    Tipo
    Tenés el espacio que es tuyo
    El que es de otro
    Y el que no es de nadie
    Este es el que reservaste y que estás seguro que podés usar
    Este es el que te tira segmentation fault cuando tratás de usarlo
    Este también podés usarlo, pero nadie te garantiza que va a estar ahí
    Vos estás usando ese
 
    En condiciones normales no hay forma
    Sólo asegurarte de pedir toda la memoria que vayas a usar
    Cero que si usás valgrind te tira que estás haciendo una escritura inválida
    #+END_EXAMPLE

*** Referencias
    + [[http://www.it.uc3m.es/pbasanta/asng/course_notes/memory_profiler_es.html][Perfilador de memoria Valgrind - Arquitectura de Sistemas uc3m]]
** Parametros a un programa en C
   + Los parámetros se pasan al momento de ejecutar el programa
   + El programa se ejecuta a partir de una linea de comando en una terminal

   #+NAME: Ejemplo - Pasar parametros a un programa en C
   #+BEGIN_SRC C
   #+END_SRC

*** Referencias
    + [[https://flaviocopes.com/c-parameters-command-line/][Parametros a un programa en C - flaviocopes.com]]
    + [[https://www.studytonight.com/c/command-line-argument.php][Command Line Argument in C - studytonight.com]]
* Imagenes

file:images/malloc.jpg

* Referencias
+ [[https://docs.google.com/document/d/1gevO2s8HmfGwmvLv3LyWmIS3j1XdgHEBzP66pihvKGY/edit#][Manejo de Punteros y Memoria Dinámica en C]]
+ [[http://www.cplusplus.com/reference/cstring/memcpy/][Función memcpy - cplusplus.com]]
* Dudas para Bender
** Paréntesis en Punteros

   #+NAME: Duda 1
   #+BEGIN_SRC C
     (*unaVariable) = (*unaVariable) + 1;

     *unaVariable = *unaVariable + 1;
   #+END_SRC

   #+NAME: Comentario de la duda 1
   #+BEGIN_EXAMPLE
   Arrojan el mismo resultado, pero porque en el ejemplo que vimos agregan el paréntesis,
   en especial el paréntesis de la izquierda (valorL)
   #+END_EXAMPLE
